### ISSUE TITLE
Cannot get pid, tid or procName at all.

### ISSUE THREAD

**Issue by edwin-koh** [KDAB/ctf2ctf#14]
When I get json file from ctf2ctf all its pid and tid is -1. And Cannot get procNames neither. 

What I need is userspace trace for Qt, so I've run followings.
```
lttng create -o /tmp/lttng/$(date -Iseconds)
lttng enable-channel ust -u
lttng enable-event -c ust -u -a
lttng add-context --userspace --type=vpid --type=vtid
```

But I've got is 
```
...
    {"name": "qtcore:QCoreApplicationPrivate_init", "ph": "B", "ts": 1586240365704353.2, "pid": -1, "tid": -1, "cat": "qtcore"},
...
```

Components I've used are  
qtbase 5.13
lttng 2.10.2
babeltrace 1.5.5

**Comment by milianw** [comment]
You also need to enable the kernel trace points, since that's where the pid/tid mapping comes from.

Alternatively you could try to add support for vpid/vtid to ctf2ctf, though afaik that wouldn't include the comm's then (i.e. process names)?

**Comment by edwin-koh** [comment]
Thanks milianw.

I've added 
```
lttng enable-channel kernel -k
lttng enable-event -c kernel -k "sched_switch,sched_process_*" 
lttng enable-event -c kernel -k --syscall -a
...
./ctf2ctf -o trace.json /tmp/lttng/2020-04-07T22\:36\:14-07\:00/
```
but, still got no pid.
I think "lttng_statedump_*" is not supported in my version of lttng.

Could you show me which kerenl event I need?

**Comment by milianw** [comment]
Can you just try with `lttng enable-event -c kernel -k -a` and see how far you get with that? The statedump should be part of the lttng tracepoints that are available through `lttng-modules`, what version are you using?

Can you share a (compressed) LTTng trace with me so I can see what is in there and what's missing?

**Comment by r0mko** [comment]
This issue is addressed in this [pull request](https://github.com/KDAB/ctf2ctf/pull/15) 
Passing the --ctx flag to the commandline will make ctf2ctf to take pid and tid information from LTTng event context. Please note that these properties (vpid and vtid) must be added to your UST channel.
